index:
    path: /
    controller: App\Controller\DashboardController::main

app_register:
     path: /register
     controller: App\Controller\RegistrationController::register

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    
app_logout:
    path: /logout
    methods: GET

app_admin:
    path: /admin
    controller: App\Controller\AdminController::index

app_admin_security:
    path: /admin/security
    controller: App\Controller\AdminController::security
    
app_admin_security_user:
    path: /admin/security/users
    controller: App\Controller\AdminController::userList

app_admin_security_user_manage:
    path: /admin/security/users/{id}/manage
    controller: App\Controller\AdminController::userManage
    
app_admin_security_user_manage_activate:
    path: /admin/security/users/{id}/manage/activate
    controller: App\Controller\AdminController::userActivate

app_admin_security_user_manage_deactivate:
    path: /admin/security/users/{id}/manage/deactivate
    controller: App\Controller\AdminController::userDeactivate

app_admin_security_user_manage_attach_role:
    path: /admin/security/users/{id}/manage/attach-role
    controller: App\Controller\AdminController::attachRole

app_admin_security_user_manage_detach_role:
    path: /admin/security/users/{userId}/manage/detach-role/{roleId}
    controller: App\Controller\AdminController::detachRole
    methods: GET
    requirements:
        userId: '\d+'
        roleId: '\d+'

app_admin_security_role:
    path: /admin/security/roles
    controller: App\Controller\AdminController::role

app_admin_security_role_create:
    path: /admin/security/roles/create
    controller: App\Controller\AdminController::createRole

app_admin_security_permission:
    path: /admin/security/permissions
    controller: App\Controller\AdminController::permission

app_admin_security_permission_create:
    path: /admin/security/permissions/create
    controller: App\Controller\AdminController::createPermission

app_admin_security_permission_delete:
    path: /admin/security/permissions/{id}/delete
    controller: App\Controller\AdminController::deletePermission

app_admin_security_role_manage:
    path: /admin/security/roles/{id}/manage
    controller: App\Controller\AdminController::roleManage

app_admin_security_role_manage_attach_permission:
    path: /admin/security/roles/{id}/manage/attach-permissions
    controller: App\Controller\AdminController::permissionAttach

app_admin_security_role_manage_detach_permission:
    path: /admin/security/roles/{role_id}/manage/detach-permission/{permission_id}
    controller: App\Controller\AdminController::detachPermission
    
app_admin_skill:
    path: /admin/skills
    controller: App\Controller\AdminController::skill

app_admin_skill_soft:
    path: /admin/skills/soft
    controller: App\Controller\AdminController::skillSoft

app_admin_skill_technical:
    path: /admin/skills/technical
    controller: App\Controller\AdminController::skillTechnical

app_admin_skill_soft_create:
    path: /admin/skills/soft/create
    controller: App\Controller\AdminController::skillSoftCreate

app_admin_skill_technical_create:
    path: /admin/skills/technical/create
    controller: App\Controller\AdminController::skillTechnicalCreate

app_admin_skill_technical_delete:
    path: /admin/skills/technical/{id}/delete
    controller: App\Controller\AdminController::skillTechnicalDelete

app_admin_skill_soft_delete:
    path: /admin/skills/soft/{id}/delete
    controller: App\Controller\AdminController::skillSoftDelete

app_admin_skill_soft_update:
    path: /admin/skills/soft/{id}/update
    controller: App\Controller\AdminController::skillSoftUpdate

app_admin_skill_technical_update:
    path: /admin/skills/technical/{id}/update
    controller: App\Controller\AdminController::skillTechnicalUpdate

app_admin_security_role_update:
    path: /admin/security/roles/{id}/edit
    controller: App\Controller\AdminController::roleUpdate

app_dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::main

app_dashboard_task:
    path: /dashboard/tasks
    controller: App\Controller\TaskController::main

app_dashboard_task_create_ajax_team:
    path: /dashboard/tasks/create/ajax/team/{project_id}
    controller: App\Controller\TaskController::teamByProject
    requirements:
        project_id: '\d+'

app_dashboard_task_create:
    path: /dashboard/tasks/create
    controller: App\Controller\TaskController::create\

app_dashboard_task_update:
    path: /dashboard/tasks/update/{id}
    controller: App\Controller\TaskController::update

app_dashboard_team:
    path: /dashboard/teams
    controller: App\Controller\TeamController::main

app_dashboard_team_create:
    path: /dashboard/teams/create
    controller: App\Controller\TeamController::create

app_dashboard_team_manage:
    path: /dashboard/teams/{id}/manage
    controller: App\Controller\TeamController::manage

app_dashboard_team_manage_add_member:
    path: /dashboard/teams/{id}/manage/add-member
    controller: App\Controller\TeamController::addMember

app_dashboard_team_manage_delete_member:
    path: /dashboard/teams/{team_id}/manage/delete-member/{member_id}
    controller: App\Controller\TeamController::deleteTeamMember

app_dashboard_project:
    path: /dashboard/projects
    controller: App\Controller\ProjectController::main

app_dashboard_project_create:
    path: /dashboard/projects/create
    controller: App\Controller\ProjectController::create

app_dashboard_check_list:
    path: /dashboard/task/{id}/check-list
    controller: App\Controller\MarkController::checkList
    requirements:
        id: '\d+'

app_dashboard_history_incoming:
    path: /dashboard/history/incoming
    controller: App\Controller\MarkController::historyIncoming

app_dashboard_history_outcoming:
    path: /dashboard/history/outcoming
    controller: App\Controller\MarkController::historyOutcoming

app_dashboard_history_incoming_detail:
    path: /dashboard/history/incoming/task/{id}
    controller: App\Controller\MarkController::historyIncomingDetail
    requirements:
        id: '\d+'

app_dashboard_history_outcoming_detail:
    path: /dashboard/history/outcoming/task/{id}
    controller: App\Controller\MarkController::historyOutcomingDetail
    requirements:
        id: '\d+'

